'use client';

/**
 * PROFILE COMPLETION MODAL
 *
 * Appears for new users whose profiles are incomplete (auto-generated username,
 * missing display name). Guides them through personalizing their identity in 3 steps:
 *
 * Step 1: Identity (required) - username, display name
 * Step 2: About You (optional) - bio, location, website
 * Step 3: Get Started (confirmation) - summary + quick links
 *
 * Saves on each step transition so progress is never lost.
 * Cat personality in copy throughout.
 *
 * Created: 2026-03-28
 */

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import Button from '@/components/ui/Button';
import { ArrowLeft, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import type { Profile } from '@/types/database';

import { useProfileCompletionForm, STEPS, TOTAL_STEPS } from './useProfileCompletionForm';
import { IdentityStep } from './IdentityStep';
import { AboutStep } from './AboutStep';
import { GetStartedStep } from './GetStartedStep';

// --- Types ---

interface ProfileCompletionModalProps {
  open: boolean;
  onComplete: () => void;
  profile: Profile;
  userId: string;
}

// --- Helpers ---

/**
 * Checks if a username looks auto-generated from an email prefix.
 * Auto-generated usernames are the part before @ in email, or user_XXXXXXXX.
 */
function isAutoGeneratedUsername(
  username: string | null | undefined,
  email?: string | null
): boolean {
  if (!username) {
    return true;
  }
  // Pattern: user_XXXXXXXX
  if (/^user_[a-f0-9]{8}$/i.test(username)) {
    return true;
  }
  // If username matches email prefix exactly, it was auto-generated
  if (email) {
    const emailPrefix = email.split('@')[0];
    if (username === emailPrefix) {
      return true;
    }
  }
  return false;
}

/**
 * Determines whether a profile is "incomplete" enough to show the modal.
 * True if name is missing/default OR username is auto-generated.
 */
export function isProfileIncomplete(profile: Profile | null, userEmail?: string | null): boolean {
  if (!profile) {
    return true;
  }
  const nameIncomplete = !profile.name || profile.name === 'User' || profile.name.trim() === '';
  const usernameIncomplete = isAutoGeneratedUsername(profile.username, userEmail);
  return nameIncomplete || usernameIncomplete;
}

// --- Component ---

export function ProfileCompletionModal({
  open,
  onComplete,
  profile,
  userId,
}: ProfileCompletionModalProps) {
  const form = useProfileCompletionForm(profile, onComplete);

  const { currentStep, step, isLastStep, saving, errors } = form;

  return (
    <Dialog
      open={open}
      onOpenChange={() => {
        // Allow closing only from the last step or via skip
      }}
    >
      <DialogContent
        className="sm:max-w-[480px] max-h-[90vh] overflow-y-auto"
        onPointerDownOutside={e => e.preventDefault()}
        onEscapeKeyDown={e => {
          if (!isLastStep) {
            e.preventDefault();
          }
        }}
      >
        <DialogHeader>
          <DialogTitle className="text-xl">{step.title}</DialogTitle>
          <DialogDescription>{step.subtitle}</DialogDescription>
        </DialogHeader>

        {/* Progress indicator */}
        <div className="flex items-center gap-1.5 py-1">
          {STEPS.map((s, idx) => (
            <div
              key={s.id}
              className={cn(
                'h-1.5 rounded-full flex-1 transition-colors',
                idx <= currentStep ? 'bg-tiffany-500' : 'bg-muted'
              )}
            />
          ))}
          <span className="text-xs text-muted-dim ml-2 flex-shrink-0">
            {currentStep + 1} of {TOTAL_STEPS}
          </span>
        </div>

        {/* General error */}
        {errors.general && (
          <div className="rounded-md oc-error-surface p-3">
            <p className="text-sm text-destructive/80">{errors.general}</p>
          </div>
        )}

        {/* Step content */}
        <div className="py-2">
          {currentStep === 0 && (
            <IdentityStep
              userId={userId}
              username={form.username}
              displayName={form.displayName}
              avatarUrl={form.avatarUrl}
              errors={errors}
              onUsernameChange={form.setUsername}
              onDisplayNameChange={form.setDisplayName}
              onAvatarUpload={form.setAvatarUrl}
            />
          )}
          {currentStep === 1 && (
            <AboutStep
              bio={form.bio}
              locationCity={form.locationCity}
              website={form.website}
              onBioChange={form.setBio}
              onLocationCityChange={form.setLocationCity}
              onWebsiteChange={form.setWebsite}
            />
          )}
          {currentStep === 2 && (
            <GetStartedStep
              displayName={form.displayName}
              username={form.username}
              bio={form.bio}
              locationCity={form.locationCity}
              onQuickAction={form.handleQuickAction}
            />
          )}
        </div>

        {/* Navigation */}
        <div className="flex items-center justify-between pt-2">
          <div>
            {currentStep > 0 && !isLastStep && (
              <Button variant="ghost" size="sm" onClick={form.handlePrevious} disabled={saving}>
                <ArrowLeft className="h-4 w-4 mr-1" />
                Back
              </Button>
            )}
          </div>

          <div className="flex items-center gap-2">
            {/* Skip for optional steps */}
            {!step.required && !isLastStep && (
              <Button variant="ghost" size="sm" onClick={form.handleSkipStep} disabled={saving}>
                Skip for now
              </Button>
            )}

            {isLastStep ? (
              <Button variant="primary" onClick={form.handleComplete}>
                Looks good!
              </Button>
            ) : (
              <Button variant="primary" onClick={form.handleNext} disabled={saving}>
                {saving && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
                {currentStep === 0 ? 'Continue' : 'Save & Continue'}
              </Button>
            )}
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}

export default ProfileCompletionModal;
